name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches: 
      - master 
      - main
      
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: General metrics
        uses: GTazz/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.base.svg
          base: header, activity, community
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_limit: 20
          plugin_languages_details: >-
            bytes-size, percentage
          plugin_languages_ignored: >-
            portugol, html, css
          repositories_skipped: >-
            estudo-booleano, Atividade-turismo-SP, estudo-de-compressao
          config_order: base.header, isocalendar, base.activity+community, languages
